/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uhu.amc1b;

import java.awt.Cursor;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author diego
 */
public class OpcionE extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public OpcionE() {
        initComponents();
        grupo1.add(b00);
        grupo1.add(b01);
        grupo1.add(b02);
        grupo1.add(b03);
        b00.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        grupo2 = new javax.swing.ButtonGroup();
        b01 = new javax.swing.JRadioButton();
        b00 = new javax.swing.JRadioButton();
        bok = new javax.swing.JButton();
        lab1 = new javax.swing.JLabel();
        b03 = new javax.swing.JRadioButton();
        b02 = new javax.swing.JRadioButton();
        bcancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b01.setText("Poda");

        b00.setText("Exhaustivo");

        bok.setText("OK");
        bok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bokActionPerformed(evt);
            }
        });

        lab1.setText("Algoritmo:");

        b03.setText("DyVPlus");
        b03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b03ActionPerformed(evt);
            }
        });

        b02.setText("DyV");

        bcancel.setText("CANCEL");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b03)
                            .addComponent(b02)
                            .addComponent(b01)
                            .addComponent(b00))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bok, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bcancel)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lab1)
                .addGap(18, 18, 18)
                .addComponent(b00)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b03)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bcancel)
                    .addComponent(bok))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bokActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            //comprobar input
            int a1 = -1;
            if (b00.isSelected()) {
                a1 = 0;
            }
            if (b01.isSelected()) {
                a1 = 1;
            }
            if (b02.isSelected()) {
                a1 = 2;
            }
            if (b03.isSelected()) {
                a1 = 3;
            }
            //guardar eleccion
            String n1 = "";
            switch (a1) {
                case 0:
                    n1 = "Exhaustiva";
                    break;
                case 1:
                    n1 = "Poda";
                    break;
                case 2:
                    n1 = "DyV";
                    break;
                case 3:
                    n1 = "DyVPlus";
                    break;
            }
            //definir tallas y num de iteraciones
            int T[] = {200, 500, 1500, 3250, 5000};
            double TD[] = {200.0, 500.0, 1500.0, 3250.0, 5000.0};
            int N = 10;
            Busqueda b[][] = new Busqueda[T.length][N];
            //crear arrays
            for (int i = 0; i < T.length; i++) {
                for (int j = 0; j < N; j++) {
                    Punto tmp[] = new Punto[T[i]];
                    Punto.rellenar(tmp, T[i], Menu.peor);
                    b[i][j] = new Busqueda(tmp);
                }
            }
            //hacer busquedas
            for (int i = 0; i < T.length; i++) {
                for (int j = 0; j < N; j++) {
                    switch (a1) {
                        case 0:
                            b[i][j].exhaustiva();
                            break;
                        case 1:
                            b[i][j].poda();
                            break;
                        case 2:
                            b[i][j].dyv();
                            break;
                        case 3:
                            b[i][j].dyvplus();
                            break;
                    }
                }
            }
            //calcular medias
            double[][] tablaT = new double[T.length][1];
            int[][] tablaC = new int[T.length][1];
            for (int i = 0; i < T.length; i++) {
                tablaT[i][0] = 0.0;
                tablaC[i][0] = 0;
            }
            for (int i = 0; i < T.length; i++) {
                for (int j = 0; j < N; j++) {
                    tablaT[i][0] = tablaT[i][0] + b[i][j].t[a1];
                    tablaC[i][0] = tablaC[i][0] + b[i][j].numcal[a1];
                }
            }
            System.out.println(tablaT[0][0]);
            //definir formato de salida
            DecimalFormat tp = new DecimalFormat("0.0000");
            double nanoMedia = 1000000.0 * (double) (N);
            //rellenar tabla
            String[] atributos = {"Talla",
                "Tiempo(ms)",
                "Calculadas"};
            Object[][] datos = {
                {T[0], tp.format(tablaT[0][0] / nanoMedia), tablaC[0][0] / N},
                {T[1], tp.format(tablaT[1][0] / nanoMedia), tablaC[1][0] / N},
                {T[2], tp.format(tablaT[2][0] / nanoMedia), tablaC[2][0] / N},
                {T[3], tp.format(tablaT[3][0] / nanoMedia), tablaC[3][0] / N},
                {T[4], tp.format(tablaT[4][0] / nanoMedia), tablaC[4][0] / N}
            };
            double[][] valores = {
                {TD[0], tablaT[0][0] / nanoMedia},
                {TD[1], tablaT[1][0] / nanoMedia},
                {TD[2], tablaT[2][0] / nanoMedia},
                {TD[3], tablaT[3][0] / nanoMedia},
                {TD[4], tablaT[4][0] / nanoMedia}
            };
            //mostrar tabla
            JTable t = new JTable(datos, atributos);
            t.setEnabled(false);
            JScrollPane sp = new JScrollPane(t);
            JFrame f = new JFrame();
            f.add(sp);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setBounds(700, 200, 700, 150);
            f.setTitle("Análisis - " + n1);
            f.setVisible(true);
            this.setVisible(false);
            //mostrar g
            GraficaE g = new GraficaE(valores, n1);
            g.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            g.setBounds(200, 350, 800, 400);
            g.setTitle("Representación");
            g.setVisible(true);
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        } catch (Exception e) {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_bokActionPerformed

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bcancelActionPerformed

    private void b03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b03ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new OpcionE().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b00;
    private javax.swing.JRadioButton b01;
    private javax.swing.JRadioButton b02;
    private javax.swing.JRadioButton b03;
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bok;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.ButtonGroup grupo2;
    private javax.swing.JLabel lab1;
    // End of variables declaration//GEN-END:variables
}
